#cloud-config
install:
  auto: true
  device: "/dev/sda"
  reboot: true
  poweroff: false

hostname: "kairos-demo"

users:
  - name: "kairos"
    passwd: "kairos"
    groups: ["admin"]

k3s:
  enable: true
